{% set version = "3.0.2" %}

package:
    name: uncertainties
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: 91db922d54dff6094b4ea0d6e058f713a992cdf42e3ebaf73278e1893bfa2942

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - numpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD 3-Clause
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
  recipe-maintainers:
    - ocefpaf
