{% set version = "3.2.3" %}

package:
  name: uncertainties
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: 76a5653e686f617a42922d546a239e9efce72e6b35411b7750a1d12dcba03031

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - future
    # optional
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.

extra:
  recipe-maintainers:
    - ocefpaf
