{% set version = "3.2.2" %}

package:
  name: uncertainties
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: e62c86fdc64429828229de6ab4e11466f114907e6bd343c077858994cc12e00b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - future
    # optional
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.

extra:
  recipe-maintainers:
    - ocefpaf
